### PR TITLE
Bug/tooltip bug

### LINKED ISSUE #248: Tooltip: unnecessary focus box when toggled
**Describe the bug**
Whenever the Tooltip component is toggled, there will be a focus highlight box surrounding the component.

**To Reproduce**
1. Run the docs
2. Visit Tooltip page
3. Scroll down to examples
4. Toggle the tooltip
5. See the issue

**Expected behavior**
The tooltip box should not have any surrounding highlight even if it's in focus. If the intended behavior is to toggle the tooltip on focus then the tooltip box shouldn't be the one to be highlighted. It will be the element that is the target of the tooltip. For example, an input field that comes in focus would toggle a tooltip.

**Screenshots**
Screen Shot 2020-04-09 at 2 11 51 PM

**Desktop (please complete the following information):**
 - OS: MacOS, Windows 10
 - Browser Chrome, Safari, Firefox, Edge, IE

### LINKED ISSUE #249: Tooltip: the container should not be translucent
**Describe the bug**
The tooltip container is currently translucent which it shouldn't be. There is no mention anywhere in the [Design Library Guidelines](https://designlibrary.sebgroup.com/patterns/feedback-to-the-user/guide-the-user/tooltip/#guidelines) of a tooltip container being translucent

**To Reproduce**
1. Run the docs
2. Visit Tooltip page
3. Scroll down to examples
4. Toggle the tooltip
6. Scroll the page where an item can come underneath it.
5. See the issue

**Expected behavior**
The tooltip container should be completely solid. No transparency is required.

**Screenshots**
Screen Shot 2020-04-09 at 2 29 14 PM

**Desktop (please complete the following information):**
 - OS: MacOS, Windows 10
 - Browser Chrome, Safari, Firefox, Edge, IE

### LINKED ISSUE #251: Tooltip: the container is still rendered even when it's hidden
**Describe the bug**
The tooltip container lingers around for some reason even though it's hidden

**To Reproduce**
1. Run the docs
2. Visit Tooltip page
3. Scroll down to examples
4. Switch to **Bottom** placement
5. Toggle on the tooltip with a click on the icon
6. Toggle off the tooltip with a click on the icon
7. Move a little bit underneath the tooltip and click
8. See the issue

**Expected behavior**
The tooltip should not be rendered when it's supposed to be hidden

**Screenshots**
Screen-Recording-2020-04-09-at-2 47 22-PM

**Desktop (please complete the following information):**
 - OS: MacOS, Windows 10
 - Browser Chrome, Safari, Firefox, Edge, IE

### LINKED ISSUE #252: Tooltip: invalid on-hover behavior
**Describe the bug**
The tooltip component behaves incorrectly when used in **Hover** trigger

**To Reproduce**
1. Run the docs
2. Visit Tooltip page
3. Scroll down to examples
4. Switch to **Hover** trigger
5. Hover over the tooltip icon
6. Toggle off the tooltip with a click on the icon
7. Try to toggle it back on with the icon
8. See the issue

**Expected behavior**
The tooltip should not be toggleable with a click when the trigger is set to **Hover**. In fact, the cursor should not even turn into a pointer when you hover over it.

**Screenshots**
Screen-Recording-2020-04-09-at-3 04 54-PM

**Desktop (please complete the following information):**
 - OS: MacOS, Windows 10
 - Browser Chrome, Safari, Firefox, Edge, IE

### PR DESCRIPTION
**Pull request by kherP**
fix #248 
fix #249 
fix #251 
fix #252

### CODE REVIEW

File: src/Tooltip/Tooltip.tsx [hunk 1]
```diff
@@ -84,8 +85,11 @@ export class Tooltip extends React.Component<TooltipProps, TooltipState> {
 
     onTooltipContentBlur = (e: React.FocusEvent<HTMLDivElement>): void => {
         const triggeredNode: Node = (e.relatedTarget as Node) || document.activeElement;
-        if (this.props.trigger !== "click" || !document.getElementById(this.state.referenceId).contains(triggeredNode)) {
+        const isWithinTriggerNode: boolean = document.getElementById(this.state.referenceId).contains(triggeredNode);
```
Comment (DanSallau) [inline src/Tooltip/Tooltip.tsx:88]: Is there any reason why you are using documentById here despite the fact that you have the same element using ref ?

Comment (kherP) [reply src/Tooltip/Tooltip.tsx]: no reason, the ref wasn't there in the beginning, it was added later. I replaced getElementById with ref. Nice catch!
